export const translations = {
  VsimDetailsComponent: {
    noVirtualSIM: { en: `(there is no Virtual SIM associated with this SIM)`,
      ja: `(この SIM に追加されたバーチャル SIM はありません)` },
    sessionStatus: { en: `Session status`, ja: `セッションステータス` },
    session: { en: `Session`, ja: `セッション` },
    details: { en: `Details`, ja: `詳細` },
    credentials: { en: `Credentials`, ja: `認証情報` },
    clientPeerIpAddress: { en: `Client Peer IP Address`, ja: `クライアントピア IP アドレス` },
    clientPeerPublicKey: { en: `Client Peer Public Key`, ja: `クライアントピア 公開鍵` },
    clientPeerPrivateKey: { en: `Client Peer Private Key`, ja: `クライアントピア 秘密鍵` },
    publicKey: { en: `Public Key`, ja: `公開鍵` },
    publicKeyPlaceholder: { en: `Enter your Public Key`, ja: `公開鍵を入力` },
    serverEndpoint: { en: `Server Endpoint`, ja: `サーバー エンドポイント` },
    resetVirtualSimSessionDotDotDot: { en: `Reset Virtual SIM session`, ja: `バーチャル SIM セッションのリセット` },
    resetVirtualSimSession: { en: `Reset Virtual SIM session`, ja: `バーチャル SIM セッションをリセット` },
    resetVirtualSimSessionHelpText: {
      en:
        `If you change the network configuration for your Virtual SIM, you must reset the Virtual SIM session for the settings to take effect. Your device will be briefly disconnected, and you may need to reconfigure your device if the parameter has been updated (highlighted areas).`,
      ja:
        `VPG を設定するなど、バーチャル SIM のネットワーク設定を変更した場合、設定を有効にするには、バーチャル SIM セッションをリセットする必要があります。その際、デバイスが一時的に切断され、パラメータが更新された場合(ハイライトされた箇所)は再設定が必要となります。`,
    },
    credentialDetails: { en: `Credential details`, ja: `認証情報の詳細` },
    serverPeerPublicKey: { en: `Server Peer Public Key`, ja: `サーバーピア 公開鍵` },
    detachCredentialsDotDotDot: { en: `Detach Credentials...`, ja: `認証情報のデタッチ` },
    detachCredentials: { en: `Detach Credentials`, ja: `認証情報のデタッチ` },
    addCredentials: { en: `Save Public Key`, ja: `公開鍵を保存` },
    updateCredentials: { en: `Update credentials`, ja: `公開鍵を更新` },
    updateCredentialsHelpText: {
      en:
        `Setting a custom public key or generating new credentials will overwrite the existing credentials and reset the current session. You will need to update your device’s WireGuard configuration with the new credentials in order to connect again.`,
      ja:
        `公開鍵を設定したり、新しい認証情報を生成すると、既存の認証情報が上書きされ、現在のセッションがリセットされます。再度接続するには、デバイスの WireGuard 設定を新しい認証情報で更新する必要があります。`,
    },
    attachPublicKeyHelpText: {
      en:
        `If you generated your own WireGuard credentials, update your Virtual SIM by registering the public key here.`,
      ja: `WireGuard の認証情報を生成した場合は、こちらで公開鍵を登録してバーチャル SIM を更新します。`,
    },
    generateCredentials: { en: `Generate credentials`, ja: `認証情報を生成` },
    autogenerateCredentialsHelpText: { en: `Generate a new public and private key for your Virtual SIM.`,
      ja: `バーチャル SIM の新しい公開鍵と秘密鍵を生成します。` },
    autogenerateCredentialsPrivateKeyWarning: {
      en:
        `This is the only time that the private key is shown. If you lose this private key, you can generate a new one, or update your device credentials.`,
      ja:
        `この画面を閉じると秘密鍵は二度と表示できません。秘密鍵を紛失した場合は、新しい鍵を生成するか、デバイスの認証情報を更新してください。`,
    },
    useAutoGeneratedCredentials: { en: `Use Auto-generated credentials`, ja: `自動生成された認証情報を使用` },
    followingKeysAreDisplayedOnceOnly: { en: `The following keys are displayed once only`,
      ja: `以下の鍵は一度だけ表示されます。` },
    terminateVirtualSimDotDotDot: { en: `Terminate Virtual SIM`, ja: `バーチャル SIM の解約` },
    terminateVirtualSim: { en: `Terminate Virtual SIM`, ja: `バーチャル SIM を解約する` },
    advanced: { en: `Advanced`, ja: `高度な設定` },
    terminateHelpText: {
      en:
        `This will terminate the Virtual SIM only. It will not affect any physical SIM or other subscriptions that may exist.`,
      ja:
        `これにより、バーチャル SIM のみが解約されます。バーチャル SIM 以外の SIM や他のサブスクリプションには影響しません。`,
    },
    reinitialize: { en: `Re-initialize Virtual SIM`, ja: `バーチャル SIM の再初期化` },
    reinitializeSuccessModalTitle: { en: `Virtual SIM re-initialized`, ja: `バーチャル SIM を再初期化` },
    reinitializeSuccess: { en: `Virtual SIM successfully re-initialized!`, ja: `バーチャル SIM を再初期化しました。` },
    reinitializeHelpText: {
      en:
        `If you are having trouble activating your WireGuard connection, you can re-initialize your Virtual SIM. You do not need to reconfigure your device, however your device will be briefly disconnected.`,
      ja:
        `登録されている認証情報(CLIENT PEER PUBLIC KEY)で QUORACOMM Arc のセッションが初期化されます。<br> QUORACOMM Arc のセッションが作成できないなど、接続に問題がある場合に実行してください。`,
    },
    attachCredentialSuccess: { en: `Credentials successfully updated.`, ja: `認証情報を更新しました。` },
    resetSessionSuccess: { en: `Session reset successfully.`, ja: `セッションをリセットしました。` },
    terminateVsimSuccess: { en: `Deleted Virtual SIM successfully.`, ja: `バーチャル SIM を解約しました。` },
    terminateVsimConfirmModal: {
      title: { en: `Confirm`, ja: `確認` },
      message: { en: `Are you sure you want to terminate this virtual SIM?`,
        ja: `このバーチャル SIM を解約しますか？` },
      submit: { en: `Terminate`, ja: `解約する` },
    },
    vsimIsTerminated: { en: `This Virtual SIM has been terminated.`, ja: `バーチャル SIM を解約しました。` },
  },
};
